### ISSUE TITLE
adsf-live sends the path of the changed file instead of the path of the web page

### ISSUE THREAD

**Issue by Fjan** [denisdefreyne/adsf#37]
### Steps to reproduce

1. Use nanoc with adsf-live
2. Make a change to a page

### Expected behavior

adsf-live should send the path of the web page to live reload.

### Actual behavior

adsf-live sends the path to the file [here](https://github.com/denisdefreyne/adsf/blob/625ca127b0c35d1d726a3742f72dd7e5f77d3b00/adsf-live/lib/adsf/live/web_socket_server.rb#L26)
`path: "#{Dir.pwd}#{path}"`

instead of `path: path`

### Details

You typically only want to reload the page if the change occurred on the page you are viewing. When you change a layout in nanoc it will send many changed pages over the web socket. For livereload to know if the current page changed it needs to compare `document.location.pathname` with `path`. At this time it always reloads even if no match is found, but that results in ugly flickering if many pages change. It's not hard to modify the livereload.js to only reload if the path matches, but this comparison is needlessly complicated because the file path is being sent, from which the path first needs to be extracted.

**Comment by denisdefreyne** [comment]
Ooh, I’ve seen this behavior but never managed to figure out what was causing it. Good catch!

**Comment by Fjan** [comment]
To be clear, I also needed to make a small change to the livereload.js included with rack-livereload to completely fix the issue, but that fix will be much easier if adsf-live sends the path

**Comment by denisdefreyne** [comment]
See #38 — This is now merged (see e2b15cd006b18d2cdeef682867dfc984f692bbf3). I’ll do a release soon. Thank you!

**Comment by denisdefreyne** [comment]
This is fixed in the adsf 1.5.1 release.
