### ISSUE TITLE
Replace abandoned rack-livereload gem

### ISSUE THREAD

**Issue by Fjan** [denisdefreyne/adsf#39]
Rack-livereload still works but not very well: it outputs HTML4 and is locked to an older rack version and does not seem to get further updates. It can be replaced by a simple piece of rack middleware.

I've attached a PR here: https://github.com/denisdefreyne/adsf/pull/38

It also fixes issue https://github.com/denisdefreyne/adsf/issues/37 where it was sending a path instead of a URL.

**Comment by denisdefreyne** [comment]
See #38 — This is now merged (see e2b15cd006b18d2cdeef682867dfc984f692bbf3). I’ll do a release soon. Thank you!

**Comment by denisdefreyne** [comment]
This is fixed in the adsf 1.5.1 release.
